package com.kun.github.presentation.settings

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalContext
import com.kun.github.R

/**
 * 多语言字符串集合
 */
data class AppStrings(
    // 导航
    val navHome: String,
    val navStars: String,
    val navProfile: String,
    val navDeploy: String,
    
    // 首页
    val homeTitle: String,
    val homeCreateRepo: String,
    val homeEmptyTitle: String,
    val homeEmptyDesc: String,
    
    // 星标
    val starsTitle: String,
    val starsEmptyTitle: String,
    val starsEmptyDesc: String,
    
    // 排序
    val sortUpdated: String,
    val sortStars: String,
    val sortForks: String,
    val sortName: String,
    
    // 仓库操作
    val repoPin: String,
    val repoUnpin: String,
    val repoSettings: String,
    val repoBranches: String,
    val repoTags: String,
    val repoCopyLink: String,
    val repoDownloadZip: String,
    val repoDelete: String,
    val repoFork: String,
    val repoForking: String,
    val repoPrivate: String,
    val repoUpdatedAt: String, // "更新于 %s"
    
    // 设置
    val settingsTitle: String,
    val settingsAppearance: String,
    val settingsDarkMode: String,
    val settingsLight: String,
    val settingsDark: String,
    val settingsSystem: String,
    val settingsLanguage: String,
    val settingsDataManage: String,
    val settingsClearCache: String,
    val settingsOthers: String,
    val settingsAbout: String,
    val settingsSelectLanguage: String,
    val settingsCacheCleared: String,
    
    // 语言
    val langSystem: String,
    val langChinese: String,
    val langEnglish: String,
    
    // 通用
    val confirm: String,
    val cancel: String,
    val delete: String,
    val save: String,
    val retry: String,
    val close: String,
    val logout: String,
    val logoutConfirm: String,
    val logoutMessage: String,
    
    // 网络错误
    val networkErrorTitle: String,
    val networkErrorDesc: String,
    
    // 对话框
    val deleteRepoTitle: String,
    val deleteRepoMessage: String, // "确定要删除仓库「%s」吗？..."
    val repoSettingsTitle: String,
    val repoSettingsBasic: String,
    val repoSettingsFeatures: String,
    val repoSettingsName: String,
    val repoSettingsDesc: String,
    val repoSettingsHomepage: String,
    val repoSettingsPrivate: String,
    val repoSettingsIssues: String,
    val repoSettingsWiki: String,
    val repoSettingsDiscussions: String,
    
    // Toast
    val toastRepoCreated: String,
    val toastRepoDeleted: String,
    val toastRepoUpdated: String,
    val toastLinkCopied: String,
    val toastForkSuccess: String,
    val toastForkFailed: String,
    val toastNoBranches: String,
    val toastNoTags: String,
    
    // 时间
    val timeJustNow: String,
    val timeMinutesAgo: String, // "%d分钟前"
    val timeHoursAgo: String,
    val timeDaysAgo: String,
    val timeWeeksAgo: String,
    val timeMonthsAgo: String,
    val timeYearsAgo: String,

    // 通知
    val notificationsTitle: String,
    val notificationsEmpty: String,
    val notificationsMarkedRead: String,
    val notificationTypeIssue: String,
    val notificationTypePR: String,
    val notificationTypeCommit: String,
    val notificationTypeRelease: String,
    val notificationTypeDiscussion: String,
    val notificationTypeOther: String,
    val notificationReasonSubscribed: String,
    val notificationReasonManual: String,
    val notificationReasonAuthor: String,
    val notificationReasonComment: String,
    val notificationReasonMention: String,
    val notificationReasonTeamMention: String,
    val notificationReasonReviewRequested: String,
    val notificationReasonSecurityAlert: String,

    // 部署
    val deployTitle: String,
    val deploySubtitle: String,
    val deployEmptyRepos: String,
    val deployRequestSent: String,
    val deployFailed: String,
    val deployDeploying: String,
    val deployChecking: String,
    val deployDeployed: String,
    val deployNotDeployed: String,
    val deployClickToDeploy: String,
    val deployOwnerOnly: String,
    val deployStart: String,
    val deployRedeploy: String,
    val deployVisit: String,
    val deploySettings: String,
    val deployBranch: String,
    val deploySelectBranch: String,
    val deployCustomDomain: String,
    val deployCustomDomainHint: String,
    val deploySaveDomain: String,
    val deployDomainUpdated: String,
    val deployUpdateFailed: String,
    val deployStatus: String,
    val deployUrl: String,
    val deployCopied: String,
    val deployOpen: String,
    val deployBack: String,

    // 关于
    val aboutTitle: String,
    val aboutTermsOfService: String,
    val aboutPrivacyPolicy: String,
    val aboutLibraries: String,
    val aboutCheckUpdate: String,
    val aboutDeveloper: String,
    val aboutUiFramework: String,
    val aboutDesignComponents: String,
    val aboutNetworkRequest: String,
    val aboutHttpClient: String,
    val aboutImageLoading: String,
    val aboutJsonSerialization: String,
    val aboutDataStorage: String,
    val aboutSplashScreen: String,
)

/**
 * 中文
 */
val ChineseStrings = AppStrings(
    navHome = "我的仓库",
    navStars = "星标",
    navProfile = "我的",
    navDeploy = "部署",
    homeTitle = "我的仓库",
    homeCreateRepo = "创建仓库",
    homeEmptyTitle = "还没有仓库",
    homeEmptyDesc = "你还没有创建任何仓库。\n创建第一个仓库开始管理你的代码吧！",
    starsTitle = "我的星标",
    starsEmptyTitle = "还没有星标",
    starsEmptyDesc = "你还没有星标任何仓库。\n发现有趣的仓库并星标它们吧！",
    sortUpdated = "最近更新",
    sortStars = "最多星标",
    sortForks = "最多复刻",
    sortName = "名称排序",
    repoPin = "置顶仓库",
    repoUnpin = "取消置顶",
    repoSettings = "仓库设置",
    repoBranches = "分支管理",
    repoTags = "版本管理",
    repoCopyLink = "仓库链接",
    repoDownloadZip = "下载 ZIP",
    repoDelete = "删除仓库",
    repoFork = "复刻仓库",
    repoForking = "复刻中…",
    repoPrivate = "私有",
    repoUpdatedAt = "更新于 %s",
    settingsTitle = "设置",
    settingsAppearance = "外观",
    settingsDarkMode = "深色模式",
    settingsLight = "浅色",
    settingsDark = "深色",
    settingsSystem = "跟随系统",
    settingsLanguage = "语言",
    settingsDataManage = "数据管理",
    settingsClearCache = "清除缓存",
    settingsOthers = "其他",
    settingsAbout = "关于",
    settingsSelectLanguage = "选择语言",
    settingsCacheCleared = "缓存已清除",
    langSystem = "跟随系统",
    langChinese = "简体中文",
    langEnglish = "English",
    confirm = "确认",
    cancel = "取消",
    delete = "删除",
    save = "保存",
    retry = "重试",
    close = "关闭",
    logout = "退出登录",
    logoutConfirm = "退出登录",
    logoutMessage = "确定要退出当前账号吗？",
    networkErrorTitle = "网络连接失败",
    networkErrorDesc = "无法连接到服务器，请检查网络设置后重试。",
    deleteRepoTitle = "删除仓库",
    deleteRepoMessage = "确定要删除仓库「%s」吗？\n\n此操作不可撤销，所有数据将被永久删除。",
    repoSettingsTitle = "仓库设置",
    repoSettingsBasic = "基本信息",
    repoSettingsFeatures = "功能",
    repoSettingsName = "名称",
    repoSettingsDesc = "描述",
    repoSettingsHomepage = "主页 URL",
    repoSettingsPrivate = "私有仓库",
    repoSettingsIssues = "Issues",
    repoSettingsWiki = "Wiki",
    repoSettingsDiscussions = "Discussions",
    toastRepoCreated = "仓库创建成功",
    toastRepoDeleted = "仓库已删除",
    toastRepoUpdated = "保存成功",
    toastLinkCopied = "已复制仓库链接",
    toastForkSuccess = "复刻成功",
    toastForkFailed = "复刻失败",
    toastNoBranches = "暂无分支",
    toastNoTags = "暂无版本标签",
    timeJustNow = "刚刚",
    timeMinutesAgo = "%d分钟前",
    timeHoursAgo = "%d小时前",
    timeDaysAgo = "%d天前",
    timeWeeksAgo = "%d周前",
    timeMonthsAgo = "%d个月前",
    timeYearsAgo = "%d年前",

    // 通知
    notificationsTitle = "通知",
    notificationsEmpty = "暂无通知",
    notificationsMarkedRead = "已标记为已读",
    notificationTypeIssue = "Issue",
    notificationTypePR = "Pull Request",
    notificationTypeCommit = "Commit",
    notificationTypeRelease = "Release",
    notificationTypeDiscussion = "Discussion",
    notificationTypeOther = "其他",
    notificationReasonSubscribed = "订阅",
    notificationReasonManual = "手动",
    notificationReasonAuthor = "作者",
    notificationReasonComment = "评论",
    notificationReasonMention = "提及",
    notificationReasonTeamMention = "团队提及",
    notificationReasonReviewRequested = "请求审查",
    notificationReasonSecurityAlert = "安全提醒",

    // 部署
    deployTitle = "部署",
    deploySubtitle = "选择仓库启用 GitHub Pages 部署",
    deployEmptyRepos = "暂无仓库",
    deployRequestSent = "部署请求已发送",
    deployFailed = "部署失败",
    deployDeploying = "部署中...",
    deployChecking = "检查中...",
    deployDeployed = "已部署",
    deployNotDeployed = "未部署",
    deployClickToDeploy = "点击右侧按钮部署",
    deployOwnerOnly = "仅所有者可部署",
    deployStart = "开始部署",
    deployRedeploy = "重新部署",
    deployVisit = "访问",
    deploySettings = "部署设置",
    deployBranch = "部署分支",
    deploySelectBranch = "选择要部署的分支",
    deployCustomDomain = "自定义域名",
    deployCustomDomainHint = "绑定自定义域名（需在 DNS 配置 CNAME 记录）",
    deploySaveDomain = "保存域名",
    deployDomainUpdated = "域名已更新，部署后生效",
    deployUpdateFailed = "更新失败",
    deployStatus = "状态",
    deployUrl = "访问地址",
    deployCopied = "已复制",
    deployOpen = "打开",
    deployBack = "返回",

    // 关于
    aboutTitle = "关于",
    aboutTermsOfService = "用户协议",
    aboutPrivacyPolicy = "隐私政策",
    aboutLibraries = "使用的库",
    aboutCheckUpdate = "检查更新",
    aboutDeveloper = "开发者：kun",
    aboutUiFramework = "UI 框架",
    aboutDesignComponents = "设计组件",
    aboutNetworkRequest = "网络请求",
    aboutHttpClient = "HTTP 客户端",
    aboutImageLoading = "图片加载",
    aboutJsonSerialization = "JSON 序列化",
    aboutDataStorage = "数据存储",
    aboutSplashScreen = "启动屏",
)

/**
 * 英文
 */
val EnglishStrings = AppStrings(
    navHome = "Repositories",
    navStars = "Stars",
    navProfile = "Profile",
    navDeploy = "Deploy",
    homeTitle = "Repositories",
    homeCreateRepo = "Create",
    homeEmptyTitle = "No Repositories",
    homeEmptyDesc = "You haven't created any repositories yet.\nCreate your first repository to get started!",
    starsTitle = "Stars",
    starsEmptyTitle = "No Stars",
    starsEmptyDesc = "You haven't starred any repositories yet.\nDiscover and star interesting repositories!",
    sortUpdated = "Recently Updated",
    sortStars = "Most Stars",
    sortForks = "Most Forks",
    sortName = "Name",
    repoPin = "Pin Repository",
    repoUnpin = "Unpin Repository",
    repoSettings = "Settings",
    repoBranches = "Branches",
    repoTags = "Tags",
    repoCopyLink = "Copy Link",
    repoDownloadZip = "Download ZIP",
    repoDelete = "Delete",
    repoFork = "Fork",
    repoForking = "Forking…",
    repoPrivate = "Private",
    repoUpdatedAt = "Updated %s",
    settingsTitle = "Settings",
    settingsAppearance = "Appearance",
    settingsDarkMode = "Dark Mode",
    settingsLight = "Light",
    settingsDark = "Dark",
    settingsSystem = "System",
    settingsLanguage = "Language",
    settingsDataManage = "Data",
    settingsClearCache = "Clear Cache",
    settingsOthers = "Other",
    settingsAbout = "About",
    settingsSelectLanguage = "Select Language",
    settingsCacheCleared = "Cache cleared",
    langSystem = "System",
    langChinese = "简体中文",
    langEnglish = "English",
    confirm = "Confirm",
    cancel = "Cancel",
    delete = "Delete",
    save = "Save",
    retry = "Retry",
    close = "Close",
    logout = "Log Out",
    logoutConfirm = "Log Out",
    logoutMessage = "Are you sure you want to log out?",
    networkErrorTitle = "Network Error",
    networkErrorDesc = "Unable to connect to the server. Please check your network settings.",
    deleteRepoTitle = "Delete Repository",
    deleteRepoMessage = "Are you sure you want to delete \"%s\"?\n\nThis action cannot be undone.",
    repoSettingsTitle = "Repository Settings",
    repoSettingsBasic = "Basic Info",
    repoSettingsFeatures = "Features",
    repoSettingsName = "Name",
    repoSettingsDesc = "Description",
    repoSettingsHomepage = "Homepage URL",
    repoSettingsPrivate = "Private",
    repoSettingsIssues = "Issues",
    repoSettingsWiki = "Wiki",
    repoSettingsDiscussions = "Discussions",
    toastRepoCreated = "Repository created",
    toastRepoDeleted = "Repository deleted",
    toastRepoUpdated = "Saved",
    toastLinkCopied = "Link copied",
    toastForkSuccess = "Forked successfully",
    toastForkFailed = "Fork failed",
    toastNoBranches = "No branches",
    toastNoTags = "No tags",
    timeJustNow = "just now",
    timeMinutesAgo = "%dm ago",
    timeHoursAgo = "%dh ago",
    timeDaysAgo = "%dd ago",
    timeWeeksAgo = "%dw ago",
    timeMonthsAgo = "%dmo ago",
    timeYearsAgo = "%dy ago",

    // Notifications
    notificationsTitle = "Notifications",
    notificationsEmpty = "No notifications",
    notificationsMarkedRead = "Marked as read",
    notificationTypeIssue = "Issue",
    notificationTypePR = "Pull Request",
    notificationTypeCommit = "Commit",
    notificationTypeRelease = "Release",
    notificationTypeDiscussion = "Discussion",
    notificationTypeOther = "Other",
    notificationReasonSubscribed = "Subscribed",
    notificationReasonManual = "Manual",
    notificationReasonAuthor = "Author",
    notificationReasonComment = "Comment",
    notificationReasonMention = "Mention",
    notificationReasonTeamMention = "Team Mention",
    notificationReasonReviewRequested = "Review Requested",
    notificationReasonSecurityAlert = "Security Alert",

    // Deploy
    deployTitle = "Deploy",
    deploySubtitle = "Select a repository to enable GitHub Pages",
    deployEmptyRepos = "No repositories",
    deployRequestSent = "Deploy request sent",
    deployFailed = "Deploy failed",
    deployDeploying = "Deploying...",
    deployChecking = "Checking...",
    deployDeployed = "Deployed",
    deployNotDeployed = "Not deployed",
    deployClickToDeploy = "Click button to deploy",
    deployOwnerOnly = "Only owner can deploy",
    deployStart = "Deploy",
    deployRedeploy = "Redeploy",
    deployVisit = "Visit",
    deploySettings = "Deploy Settings",
    deployBranch = "Branch",
    deploySelectBranch = "Select branch to deploy",
    deployCustomDomain = "Custom Domain",
    deployCustomDomainHint = "Bind custom domain (CNAME record required in DNS)",
    deploySaveDomain = "Save Domain",
    deployDomainUpdated = "Domain updated, effective after deploy",
    deployUpdateFailed = "Update failed",
    deployStatus = "Status",
    deployUrl = "URL",
    deployCopied = "Copied",
    deployOpen = "Open",
    deployBack = "Back",

    // About
    aboutTitle = "About",
    aboutTermsOfService = "Terms of Service",
    aboutPrivacyPolicy = "Privacy Policy",
    aboutLibraries = "Libraries",
    aboutCheckUpdate = "Check for Updates",
    aboutDeveloper = "Developer: kun",
    aboutUiFramework = "UI Framework",
    aboutDesignComponents = "Design Components",
    aboutNetworkRequest = "Network",
    aboutHttpClient = "HTTP Client",
    aboutImageLoading = "Image Loading",
    aboutJsonSerialization = "JSON Serialization",
    aboutDataStorage = "Data Storage",
    aboutSplashScreen = "Splash Screen",
)

/**
 * 根据当前语言获取字符串集合
 */
fun getAppStrings(language: LanguageManager.AppLanguage): AppStrings {
    return when (language) {
        LanguageManager.AppLanguage.CHINESE -> ChineseStrings
        LanguageManager.AppLanguage.ENGLISH -> EnglishStrings
        LanguageManager.AppLanguage.SYSTEM -> {
            // 跟随系统时，根据系统语言选择
            val locale = java.util.Locale.getDefault()
            if (locale.language.startsWith("zh")) ChineseStrings else EnglishStrings
        }
    }
}

/**
 * CompositionLocal 用于在 Compose 中传递字符串
 */
val LocalStrings = staticCompositionLocalOf { ChineseStrings }

/**
 * 在 Compose 中获取当前字符串集合
 */
@Composable
fun strings(): AppStrings = LocalStrings.current
